services:
  redis:
    image: redis:7.4.1
    restart: on-failure
    volumes:
      - redis-storage:/data
    expose:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 10s
      start_interval: 2s

  auth:
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./auth/.env
    build: ./auth/
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD-SHELL", "httpx http://localhost:8000/api/openapi/" ]
      start_period: 5s
      start_interval: 1s
    depends_on:
      redis:
        condition: service_healthy

  content:
    restart: on-failure
    env_file:
      - ./content/.env
    environment:
      - AUTHJWT_VALIDATOR=http://auth:8000/api/v1/auth/validate
    build: ./content/
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD-SHELL", "httpx http://localhost:8000/api/openapi/" ]
      start_period: 5s
      start_interval: 1s
    depends_on:
      auth:
        condition: service_healthy

volumes:
  redis-storage:
