[tool.black]
line-length = 100

[tool.isort]
profile = "black"
src_paths = ["auth/src", "content/src"]

[tool.flake8]
max-line-length = 100

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = ["content"]
